name: HugoBuildAndDeploy

on:
  workflow_dispatch: # To have the ability to run the workflow manually

  push:
    branches: [main]

env:
  NAME: ./
  CONTAINER-NAME: fi-pv

jobs:
  ReleaseVersion:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Hugo
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          extended: true

      # Build the hugo repository
      - run: hugo
        working-directory: ./${{ env.NAME }}/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file ./${{ env.NAME }}/deployment/Dockerfile --tag lnadev/${{ env.CONTAINER-NAME }}:${{ github.run_number }}

      - name: Push the image to dockerhub
        run: docker push lnadev/${{ env.CONTAINER-NAME }}:${{ github.run_number }}

  ReleaseLatest:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Hugo
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          extended: true

      # Build the hugo repository
      - run: hugo
        working-directory: ./${{ env.NAME }}/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file ./${{ env.NAME }}/deployment/Dockerfile --tag lnadev/${{ env.CONTAINER-NAME }}:latest

      - name: Push the image to dockerhub
        run: docker push lnadev/${{ env.CONTAINER-NAME }}:latest